### ISSUE TITLE
crashing on object file

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/frame-larger-than#3]
I tried to debug a kernel issue, and ran into this: 
clang-10 -Wp,-MMD,drivers/mtd/lpddr/.lpddr2_nvm.o.d  -nostdinc -isystem /usr/lib/llvm-10/lib/clang/10.0.0/include -I/git/arm-soc/arch/arm/include -I./arch/arm/include/generated -I/git/arm-soc/include -I./include -I/git/arm-soc/arch/arm/include/uapi -I./arch/arm/include/generated/uapi -I/git/arm-soc/include/uapi -I./include/generated/uapi -include /git/arm-soc/include/linux/kconfig.h -include /git/arm-soc/include/linux/compiler_types.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Werror=strict-prototypes -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -std=gnu89 --target=arm-linux-gnueabi --prefix=/home/arnd/cross/x86_64/gcc-10.0.20200413-nolibc/arm-linux-gnueabi/bin/ --gcc-toolchain=/home/arnd/cross/x86_64/gcc-10.0.20200413-nolibc/arm-linux-gnueabi -no-integrated-as -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mfpu=vfp -funwind-tables -meabi gnu -marm -Wa,-mno-warn-deprecated -D__LINUX_ARM_ARCH__=4 -march=armv4 -mtune=arm9tdmi -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 -Wframe-larger-than=1024 -fstack-protector-strong -mno-global-merge -fomit-frame-pointer -Wdeclaration-after-statement -Wvla -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=date-time -Werror=incompatible-pointer-types -fmacro-prefix-map=/git/arm-soc/= -Werror  -I /git/arm-soc/drivers/mtd/lpddr -I ./drivers/mtd/lpddr    -DKBUILD_MODFILE='"drivers/mtd/lpddr/lpddr2_nvm"' -DKBUILD_BASENAME='"lpddr2_nvm"' -DKBUILD_MODNAME='"lpddr2_nvm"' -c -o drivers/mtd/lpddr/lpddr2_nvm.o /git/arm-soc/drivers/mtd/lpddr/lpddr2_nvm.c -Wno-error -gdwarf-2
/git/arm-soc/drivers/mtd/lpddr/lpddr2_nvm.c:399:12: warning: stack frame size of 1296 bytes in function 'lpddr2_nvm_probe' [-Wframe-larger-than=]
static int lpddr2_nvm_probe(struct platform_device *pdev)
           ^
1 warning generated.
arnd@threadripper:/git/arm-soc/build/arm/0x5D2622EE_defconfig$ frame_larger_than.py drivers/mtd/lpddr/lpddr2_nvm.o lpddr2_nvm_probe
lpddr2_nvm_probe:
	4	struct pcm_int_data*	pcm_data
	4	struct map_info*    	map
	4	struct mtd_info*    	mtd
	4	struct resource*    	add_range
	4	struct resource*    	control_regs
devm_kzalloc:
devm_kzalloc:
devm_kzalloc:
resource_size:
resource_size:
lpddr2_nvm_pfow_present:
	4	unsigned int        	found
Unsupported type info for map_word, implement me!
DIE DW_TAG_typedef, size=11, has_children=False
    |DW_AT_type        :  AttributeValue(name='DW_AT_type', form='DW_FORM_ref4', value=25444, raw_value=25444, offset=25434)
    |DW_AT_name        :  AttributeValue(name='DW_AT_name', form='DW_FORM_strp', value=b'map_word', raw_value=14301, offset=25438)
    |DW_AT_decl_file   :  AttributeValue(name='DW_AT_decl_file', form='DW_FORM_data1', value=82, raw_value=82, offset=25442)
    |DW_AT_decl_line   :  AttributeValue(name='DW_AT_decl_line', form='DW_FORM_data1', value=171, raw_value=171, offset=25443)

Traceback (most recent call last):
  File "/home/arnd/bin/frame_larger_than.py", line 149, in <module>
    parse_file(elffile.get_dwarf_info(), sys.argv[2])
  File "/home/arnd/bin/frame_larger_than.py", line 131, in parse_file
    parse_file(dwarf_info, get_name(ti))
  File "/home/arnd/bin/frame_larger_than.py", line 127, in parse_file
    print_var(dwarf_info, DIE)
  File "/home/arnd/bin/frame_larger_than.py", line 113, in print_var
    type_string = get_type_string(dwarf_info, type_info)
  File "/home/arnd/bin/frame_larger_than.py", line 90, in get_type_string
    return get_type_string(dwarf_info, pointed_to_type) + '[]'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by arndb** [comment]
This is the object file that caused the problem:

[lpddr2_nvm.o.gz](https://github.com/ClangBuiltLinux/frame-larger-than/files/4577292/lpddr2_nvm.o.gz)

**Comment by arndb** [comment]
And another file that I wanted to debug, with a similar message:
Unsupported type info for u64, implement me!
DIE DW_TAG_typedef, size=11, has_children=False
    |DW_AT_type        :  AttributeValue(name='DW_AT_type', form='DW_FORM_ref4', value=58, raw_value=58, offset=77)
    |DW_AT_name        :  AttributeValue(name='DW_AT_name', form='DW_FORM_strp', value=b'u64', raw_value=161, offset=81)
    |DW_AT_decl_file   :  AttributeValue(name='DW_AT_decl_file', form='DW_FORM_data1', value=3, raw_value=3, offset=85)
    |DW_AT_decl_line   :  AttributeValue(name='DW_AT_decl_line', form='DW_FORM_data1', value=23, raw_value=23, offset=86)

Traceback (most recent call last):
  File "/home/arnd/bin/frame_larger_than.py", line 149, in <module>
    parse_file(elffile.get_dwarf_info(), sys.argv[2])
  File "/home/arnd/bin/frame_larger_than.py", line 127, in parse_file
    print_var(dwarf_info, DIE)
  File "/home/arnd/bin/frame_larger_than.py", line 113, in print_var
    type_string = get_type_string(dwarf_info, type_info)
  File "/home/arnd/bin/frame_larger_than.py", line 90, in get_type_string
    return get_type_string(dwarf_info, pointed_to_type) + '[]'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'


[curve25519-hacl64.o.gz](https://github.com/ClangBuiltLinux/frame-larger-than/files/4577558/curve25519-hacl64.o.gz)

**Comment by nickdesaulniers** [comment]
Both cases were fixed by adding support for `DW_TAG_typedef`.
https://github.com/ClangBuiltLinux/frame-larger-than/commit/698e14926b3eadd40adb5f337d772f13d6e9d7cf
Thanks for the reports!
