### ISSUE TITLE
README.md doesn't show how to run this tool

### ISSUE THREAD

**Issue by enh-google** [ClangBuiltLinux/frame-larger-than#9]
the example implies that the kernel build somehow magically runs this tool itself :-)

**Comment by nathanchance** [comment]
Hmm I see two separate commands: one to demonstrate an example of a warning that may appear and one to show how to run the tool against an object file from the kernel tree. Any suggestions for how to make it clearer? :) Perhaps separating the commands into their own Markdown block and a short explanation of what each command is showing?

**Comment by enh-google** [comment]
oh, yeah, you're right. not being familiar with the kernel build output (and being used to a color prompt to help break up the output of different commands) i missed that.

your suggestion of breaking them into separate blocks sgtm. (though the "how to build part of the kernel" block still gives the impression that this tool is only for kernel use... don't people generally know how to get a .o file from their build? or is the kernel particularly weird/difficult there?)

**Comment by nathanchance** [comment]
I've put up https://github.com/ClangBuiltLinux/frame-larger-than/pull/10, thoughts?

> don't people generally know how to get a .o file from their build? or is the kernel particularly weird/difficult there?

Most guides for building the kernel do not really talk about it in my experience, so I am not sure how common that knowledge is within the kernel community. `make help` mentions it though.
